const mockOpenInquiries = {
  "testmode": "0",
  "openInquiry_Count": 7,
  "status_code": "200",
  "inquiries": [
      {
          "inquiryComments": "",
          "isStatusClosed": 0,
          "otherInformationType": "",
          "statusChangeDate": "March, 05 2020 00:00:00",
          "inquiryDate": "March, 05 2020 00:00:00",
          "assignedByID": 0,
          "state": "",
          "firstName": "",
          "assignedToDate": "March, 05 2020 00:00:00",
          "otherTopic": "",
          "email": "",
          "inquiryID": 56944,
          "otherInformationUse": "",
          "mediumID": 8,
          "orderID": "",
          "customerID": 101656,
          "assignedBy": "Trip Ward",
          "assignedToID": 50,
          "lastName": "",
          "assignmentNotes": "",
          "addressID": 117658,
          "assignedTo": "Trip Ward",
          "stateID": ""
      },
      {
          "inquiryComments": "",
          "isStatusClosed": 0,
          "otherInformationType": "",
          "statusChangeDate": "February, 04 2020 00:00:00",
          "inquiryDate": "February, 04 2020 00:00:00",
          "assignedByID": 85,
          "state": "",
          "firstName": "",
          "assignedToDate": "February, 04 2020 00:00:00",
          "otherTopic": "",
          "email": "",
          "inquiryID": 56912,
          "otherInformationUse": "",
          "mediumID": 2,
          "orderID": "",
          "customerID": 101618,
          "assignedBy": "Isabelle Clark",
          "assignedToID": 85,
          "lastName": "",
          "assignmentNotes": "",
          "addressID": 117617,
          "assignedTo": "Isabelle Clark",
          "stateID": ""
      },
      {
          "inquiryComments": "",
          "isStatusClosed": 0,
          "otherInformationType": "",
          "statusChangeDate": "December, 11 2020 00:00:00",
          "inquiryDate": "December, 11 2019 00:00:00",
          "assignedByID": 50,
          "state": "",
          "firstName": "",
          "assignedToDate": "December, 11 2020 00:00:00",
          "otherTopic": "",
          "email": "",
          "inquiryID": 56334,
          "otherInformationUse": "",
          "mediumID": 1,
          "orderID": 484074,
          "customerID": 101610,
          "assignedBy": "Trip Ward",
          "assignedToID": 50,
          "lastName": "",
          "assignmentNotes": "",
          "addressID": 117607,
          "assignedTo": "Trip Ward",
          "stateID": ""
      },
      {
          "inquiryComments": "",
          "isStatusClosed": 0,
          "otherInformationType": "",
          "statusChangeDate": "September, 13 2019 00:00:00",
          "inquiryDate": "September, 13 2019 00:00:00",
          "assignedByID": 50,
          "state": "California",
          "firstName": "Pawfj",
          "assignedToDate": "September, 13 2019 00:00:00",
          "otherTopic": "",
          "email": "hfjfeyatj@dsmmtlsaqnms.cvx",
          "inquiryID": 55305,
          "otherInformationUse": "",
          "mediumID": 4,
          "orderID": 480518,
          "customerID": 100680,
          "assignedBy": "Trip Ward",
          "assignedToID": 50,
          "lastName": "Gonzales",
          "assignmentNotes": "",
          "addressID": 116441,
          "assignedTo": "Trip Ward",
          "stateID": 6
      },
      {
          "inquiryComments": "",
          "isStatusClosed": 0,
          "otherInformationType": "",
          "statusChangeDate": "September, 13 2019 00:00:00",
          "inquiryDate": "September, 13 2019 00:00:00",
          "assignedByID": 50,
          "state": "",
          "firstName": "Qkvj",
          "assignedToDate": "September, 13 2019 00:00:00",
          "otherTopic": "",
          "email": "ihkfxuoxto@uamvj.exr",
          "inquiryID": 55304,
          "otherInformationUse": "",
          "mediumID": 1,
          "orderID": 480510,
          "customerID": 41841,
          "assignedBy": "Trip Ward",
          "assignedToID": 50,
          "lastName": "Ward",
          "assignmentNotes": "",
          "addressID": 50281,
          "assignedTo": "Trip Ward",
          "stateID": ""
      },
      {
          "inquiryComments": "",
          "isStatusClosed": 0,
          "otherInformationType": "",
          "statusChangeDate": "September, 12 2019 00:00:00",
          "inquiryDate": "September, 12 2019 00:00:00",
          "assignedByID": 50,
          "state": "",
          "firstName": "Tftnvfq",
          "assignedToDate": "September, 12 2019 00:00:00",
          "otherTopic": "",
          "email": "iquhgv.fppbkcco@hiq.sum",
          "inquiryID": 55289,
          "otherInformationUse": "",
          "mediumID": 1,
          "orderID": 480499,
          "customerID": 18666,
          "assignedBy": "Trip Ward",
          "assignedToID": 50,
          "lastName": "Edwards",
          "assignmentNotes": "",
          "addressID": 22926,
          "assignedTo": "Trip Ward",
          "stateID": ""
      },
      {
          "inquiryComments": "Order to cover 2019 Prev. Res. Gde. Targeted Mailing ",
          "isStatusClosed": 0,
          "otherInformationType": "",
          "statusChangeDate": "February, 19 2019 00:00:00",
          "inquiryDate": "February, 19 2019 00:00:00",
          "assignedByID": 22,
          "state": "Virginia",
          "firstName": "Mltjvadlw",
          "assignedToDate": "February, 19 2019 00:00:00",
          "otherTopic": "",
          "email": "",
          "inquiryID": 52528,
          "otherInformationUse": "",
          "mediumID": 1,
          "orderID": 466884,
          "customerID": 59743,
          "assignedBy": "Stephen Keplinger",
          "assignedToID": 22,
          "lastName": "Targeted-Mailing",
          "assignmentNotes": "",
          "addressID": 69778,
          "assignedTo": "Stephen Keplinger",
          "stateID": 54
      }
  ],
  "inquiry_Count": 7,
  "status_text": "",
  "openInquiries": [
      {
          "inquiryComments": "",
          "isStatusClosed": 0,
          "otherInformationType": "",
          "statusChangeDate": "March, 05 2020 00:00:00",
          "inquiryDate": "March, 05 2020 00:00:00",
          "assignedByID": 0,
          "state": "",
          "firstName": "",
          "assignedToDate": "March, 05 2020 00:00:00",
          "otherTopic": "",
          "email": "",
          "inquiryID": 56944,
          "otherInformationUse": "",
          "mediumID": 8,
          "orderID": "",
          "customerID": 101656,
          "assignedBy": "Trip Ward",
          "assignedToID": 50,
          "lastName": "",
          "assignmentNotes": "",
          "addressID": 117658,
          "assignedTo": "Trip Ward",
          "stateID": ""
      },
      {
          "inquiryComments": "",
          "isStatusClosed": 0,
          "otherInformationType": "",
          "statusChangeDate": "February, 04 2020 00:00:00",
          "inquiryDate": "February, 04 2020 00:00:00",
          "assignedByID": 85,
          "state": "",
          "firstName": "",
          "assignedToDate": "February, 04 2020 00:00:00",
          "otherTopic": "",
          "email": "",
          "inquiryID": 56912,
          "otherInformationUse": "",
          "mediumID": 2,
          "orderID": "",
          "customerID": 101618,
          "assignedBy": "Isabelle Clark",
          "assignedToID": 85,
          "lastName": "",
          "assignmentNotes": "",
          "addressID": 117617,
          "assignedTo": "Isabelle Clark",
          "stateID": ""
      },
      {
          "inquiryComments": "",
          "isStatusClosed": 0,
          "otherInformationType": "",
          "statusChangeDate": "December, 11 2020 00:00:00",
          "inquiryDate": "December, 11 2019 00:00:00",
          "assignedByID": 50,
          "state": "",
          "firstName": "",
          "assignedToDate": "December, 11 2020 00:00:00",
          "otherTopic": "",
          "email": "",
          "inquiryID": 56334,
          "otherInformationUse": "",
          "mediumID": 1,
          "orderID": 484074,
          "customerID": 101610,
          "assignedBy": "Trip Ward",
          "assignedToID": 50,
          "lastName": "",
          "assignmentNotes": "",
          "addressID": 117607,
          "assignedTo": "Trip Ward",
          "stateID": ""
      },
      {
          "inquiryComments": "",
          "isStatusClosed": 0,
          "otherInformationType": "",
          "statusChangeDate": "September, 13 2019 00:00:00",
          "inquiryDate": "September, 13 2019 00:00:00",
          "assignedByID": 50,
          "state": "California",
          "firstName": "Pawfj",
          "assignedToDate": "September, 13 2019 00:00:00",
          "otherTopic": "",
          "email": "hfjfeyatj@dsmmtlsaqnms.cvx",
          "inquiryID": 55305,
          "otherInformationUse": "",
          "mediumID": 4,
          "orderID": 480518,
          "customerID": 100680,
          "assignedBy": "Trip Ward",
          "assignedToID": 50,
          "lastName": "Gonzales",
          "assignmentNotes": "",
          "addressID": 116441,
          "assignedTo": "Trip Ward",
          "stateID": 6
      },
      {
          "inquiryComments": "",
          "isStatusClosed": 0,
          "otherInformationType": "",
          "statusChangeDate": "September, 13 2019 00:00:00",
          "inquiryDate": "September, 13 2019 00:00:00",
          "assignedByID": 50,
          "state": "",
          "firstName": "Qkvj",
          "assignedToDate": "September, 13 2019 00:00:00",
          "otherTopic": "",
          "email": "ihkfxuoxto@uamvj.exr",
          "inquiryID": 55304,
          "otherInformationUse": "",
          "mediumID": 1,
          "orderID": 480510,
          "customerID": 41841,
          "assignedBy": "Trip Ward",
          "assignedToID": 50,
          "lastName": "Ward",
          "assignmentNotes": "",
          "addressID": 50281,
          "assignedTo": "Trip Ward",
          "stateID": ""
      },
      {
          "inquiryComments": "",
          "isStatusClosed": 0,
          "otherInformationType": "",
          "statusChangeDate": "September, 12 2019 00:00:00",
          "inquiryDate": "September, 12 2019 00:00:00",
          "assignedByID": 50,
          "state": "",
          "firstName": "Tftnvfq",
          "assignedToDate": "September, 12 2019 00:00:00",
          "otherTopic": "",
          "email": "iquhgv.fppbkcco@hiq.sum",
          "inquiryID": 55289,
          "otherInformationUse": "",
          "mediumID": 1,
          "orderID": 480499,
          "customerID": 18666,
          "assignedBy": "Trip Ward",
          "assignedToID": 50,
          "lastName": "Edwards",
          "assignmentNotes": "",
          "addressID": 22926,
          "assignedTo": "Trip Ward",
          "stateID": ""
      },
      {
          "inquiryComments": "Order to cover 2019 Prev. Res. Gde. Targeted Mailing ",
          "isStatusClosed": 0,
          "otherInformationType": "",
          "statusChangeDate": "February, 19 2019 00:00:00",
          "inquiryDate": "February, 19 2019 00:00:00",
          "assignedByID": 22,
          "state": "Virginia",
          "firstName": "Mltjvadlw",
          "assignedToDate": "February, 19 2019 00:00:00",
          "otherTopic": "",
          "email": "",
          "inquiryID": 52528,
          "otherInformationUse": "",
          "mediumID": 1,
          "orderID": 466884,
          "customerID": 59743,
          "assignedBy": "Stephen Keplinger",
          "assignedToID": 22,
          "lastName": "Targeted-Mailing",
          "assignmentNotes": "",
          "addressID": 69778,
          "assignedTo": "Stephen Keplinger",
          "stateID": 54
      }
  ]
}

export default mockOpenInquiries;